# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/api/student/tasks?student_id=20300101
Accept: application/json

###

GET http://127.0.0.1:8000/api/student/tasks/1/summary?student_id=20300101
Accept: application/json

###
